default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: hetzalwel9

development:
  <<: *default
  database: manuras

test:
  <<: *default
  database: manuras_test